tap "drud/ddev"
tap "eth-p/software"
tap "goles/battery"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "shopify/shopify"
brew "openssl@1.1"
brew "automake"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "bats", link: false
brew "coreutils"
brew "bats-core"
brew "bison"
brew "node"
brew "bitwarden-cli"
brew "brightness"
brew "gdbm"
brew "libffi"
brew "pcre"
brew "glib"
brew "readline"
brew "python@3.9"
brew "chruby"
brew "php"
brew "composer"
brew "cowsay"
brew "diff-so-fancy"
brew "dockutil"
brew "exa"
brew "fasd"
brew "guile"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "gobject-introspection"
brew "libass"
brew "srt"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-extras"
brew "gnu-sed"
brew "go"
brew "grep"
brew "grip"
brew "gtop"
brew "httpie"
brew "libheif"
brew "imagemagick"
brew "jq"
brew "libyaml"
brew "lsd"
brew "lynx"
brew "mackup"
brew "mas"
brew "mkcert"
brew "vapoursynth"
brew "mpv"
brew "nano"
brew "neofetch"
brew "nghttp2"
brew "nss"
brew "pandoc"
brew "peco"
brew "prettier"
brew "psgrep"
brew "pv"
brew "python@3.8", link: false
brew "ruby"
brew "ruby-install"
brew "shellcheck"
brew "sphinx-doc"
brew "ssh-copy-id"
brew "stow"
brew "thefuck"
brew "toilet"
brew "tree"
brew "wget"
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
brew "drud/ddev/ddev"
brew "eth-p/software/bat-extras"
brew "goles/battery/battery"
brew "shopify/shopify/themekit"
cask "adobe-creative-cloud"
cask "airfoil"
cask "alfred"
cask "appcleaner"
cask "appzapper"
cask "audacity"
cask "audio-hijack"
cask "backblaze"
cask "bartender"
cask "betterzip"
cask "brave-browser"
cask "calibre"
cask "chronosync"
cask "clipy"
cask "codekit"
cask "colorsnapper"
cask "dash"
cask "default-folder-x"
cask "deltawalker"
cask "docker"
cask "downie"
cask "dropbox"
cask "encryptme"
cask "evernote"
cask "firefox"
cask "firefox-developer-edition"
cask "firefox-nightly"
cask "font-fira-code"
cask "font-hack"
cask "font-hack-nerd-font"
cask "font-inconsolata"
cask "font-national-park"
cask "font-raleway"
cask "forklift"
cask "garagebuy"
cask "garagesale"
cask "gitkraken"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-chrome-canary"
cask "google-chrome-dev"
cask "gpg-suite"
cask "gqrx"
cask "hammerspoon"
cask "harvest"
cask "hazel"
cask "imagealpha"
cask "imageoptim"
cask "imazing"
cask "inboard"
cask "inssider"
cask "integrity"
cask "istat-menus"
cask "iterm2"
cask "kaleidoscope"
cask "keybase"
cask "kindle"
cask "knox"
cask "lastfm"
cask "livereload"
cask "loopback"
cask "macdown"
cask "mailmate"
cask "marked"
cask "mdimagesizemdimporter"
cask "mylio"
cask "netspot"
cask "nextcloud"
cask "numi"
cask "nvalt"
cask "obsidian"
cask "omnifocus"
cask "omnioutliner"
cask "omniplan"
cask "opera"
cask "opera-developer"
cask "permute"
cask "postman"
cask "printopia"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "reaper"
cask "renamer"
cask "resilio-sync"
cask "rubitrack-pro"
cask "safari-technology-preview"
cask "satellite-eyes"
cask "scrivener"
cask "sequel-pro"
cask "signal"
cask "sketch"
cask "sketchup"
cask "skype"
cask "slack"
cask "soundsource"
cask "sourcetree"
cask "sublime-text"
cask "superduper"
cask "suspicious-package"
cask "taskpaper"
cask "telegram"
cask "textexpander"
cask "textual"
cask "tor-browser"
cask "tower"
cask "transmission"
cask "transmit"
cask "visual-studio-code"
cask "vlc"
cask "vscodium"
cask "webpquicklook"
cask "webstorm"
cask "whatsize"
cask "xquartz"
cask "zoom"
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "CARROT Weather", id: 993487541
mas "Chronicle", id: 572561420
mas "Day One", id: 1055511498
mas "Deliveries", id: 290986013
mas "Drafts", id: 1435957248
mas "EchoHam", id: 873302145
mas "Exporter for Contacts", id: 402323447
mas "Fantastical", id: 975937182
mas "GarageBand", id: 682658836
mas "GarageBuy", id: 402415186
mas "Hand Mirror", id: 1502839586
mas "Harvest", id: 506189836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "MoneyWiz", id: 1511185140
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paletter", id: 1494948845
mas "Paprika Recipe Manager 3", id: 1303222628
mas "PDFScanner", id: 410968114
mas "Pommie", id: 963504129
mas "Reeder", id: 1529448980
mas "Session", id: 1521432881
mas "Silicio", id: 933627574
mas "SiteSucker", id: 442168834
mas "SonicWall Mobile Connect", id: 822514576
mas "Tweetbot", id: 1384080005
mas "UpHabit", id: 1495261277
