# Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "shopify/shopify"

# Brews (packages)
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "bats"
brew "pcre"
brew "coreutils"
brew "cowsay"
brew "diff-so-fancy"
brew "dockutil"
brew "exa"
brew "fasd"
brew "gobject-introspection"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-extras"
brew "gnu-sed"
brew "grep"
brew "grip"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "lsd"
brew "lynx"
brew "mackup"
brew "mas"
brew "mplayer"
brew "youtube-dl"
brew "mpv"
brew "nano"
brew "neofetch"
brew "node"
brew "pandoc"
brew "peco"
brew "psgrep"
brew "pv"
brew "python@2", link: false
brew "ruby"
brew "shellcheck"
brew "ssh-copy-id", link: true
brew "stow"
brew "toilet"
brew "tree"
brew "wget"
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
brew "shopify/shopify/themekit"

# Casks (applications)
cask "1password"
cask "adobe-creative-cloud"
cask "appzapper"
cask "arq"
cask "audio-hijack"
cask "backblaze"
cask "banktivity"
cask "bartender"
cask "betterzip"
cask "brave-browser"
cask "chronosync"
cask "cleanmymac"
cask "clipy"
cask "codekit"
cask "colloquy"
cask "dash"
cask "default-folder-x"
cask "deltawalker"
cask "docker"
cask "downie"
cask "dropbox"
cask "encryptme"
cask "evernote"
cask "expandrive"
cask "firefox"
cask "firefox-nightly"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "garagebuy"
cask "garagesale"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-chrome-canary"
cask "google-chrome-dev"
cask "gpg-suite"
cask "gqrx"
cask "hammerspoon"
cask "hand-mirror"
cask "harvest"
cask "hazel"
cask "imagealpha"
cask "imageoptim"
cask "imazing"
cask "inboard"
cask "inssider"
cask "integrity"
cask "istat-menus"
cask "iterm2"
cask "kaleidoscope"
cask "keybase"
cask "kindle"
cask "knox"
cask "lastfm"
cask "launchbar"
cask "livereload"
cask "loopback"
cask "macdown"
cask "mailmate"
cask "marked"
cask "mdimagesizemdimporter"
cask "microsoft-auto-update"
cask "netspot"
cask "nextcloud"
cask "nvalt"
cask "obsidian"
cask "omnifocus"
cask "omnioutliner"
cask "omniplan"
cask "opera"
cask "opera-developer"
cask "permute"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "renamer"
cask "resilio-sync"
cask "rubitrack-pro"
cask "safari-technology-preview"
cask "satellite-eyes"
cask "scrivener"
cask "sequel-pro"
cask "signal"
cask "sketch"
cask "sketchup"
cask "skype"
cask "slack"
cask "sourcetree"
cask "sublime-text"
cask "superduper"
cask "suspicious-package"
cask "taskpaper"
cask "textexpander"
cask "textual"
cask "tor-browser"
cask "tower"
cask "transmission"
cask "transmit"
cask "visual-studio-code"
cask "vlc"
cask "webstorm"
cask "whatsize"
cask "xquartz"
cask "zoomus"

# Mac App Store applications
mas "Amphetamine", id: 937984704
mas "Chronicle Pro", id: 1280542517
mas "ColorSnapper2", id: 969418666
mas "Day One", id: 1055511498
mas "Deliveries", id: 924726344
mas "Drafts", id: 1435957248
mas "EchoHam", id: 873302145
mas "Exporter for Contacts", id: 402323447
mas "Fantastical", id: 975937182
mas "Harvest", id: 506189836
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paletter", id: 1494948845
mas "Paprika Recipe Manager 3", id: 1303222628
mas "PDFScanner", id: 410968114
mas "Pommie", id: 963504129
mas "Reeder", id: 1449412482
mas "Reeder", id: 1529448980
mas "Session", id: 1521432881
mas "Silicio", id: 933627574
mas "SonicWall Mobile Connect", id: 822514576
mas "Tweetbot", id: 1384080005
mas "UpHabit ", id: 1495261277
